config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  namespace :administrate do
    get "/", to: "dashboards#index"

    resources :categories do
      member do
        delete "destroy_cover_image"
      end
    end

    resources :authors

    resources :posts do
      member do
        delete "destroy_cover_image"
      end
    end
  end

  resources :posts, only: [:index, :show] do
    member do
      get :category
    end
    resources :comments do
      member do
        post "like"
        post "dislike"
      end
    end
  end

  resources :categories, only: [:index]

  get "/inicio", to: "welcome#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/category.rb
# frozen_string_literal: true
class Category < ApplicationRecord
  has_many :posts

  has_one_attached :cover_image
end

app/controllers/administrate/authors_controller.rb
# frozen_string_literal: true
class Administrate::AuthorsController < AdministrateController
  before_action :set_author, only: [ :show, :edit, :update, :destroy ]

  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def edit
  end

  def show
  end

  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html {
          redirect_to(administrate_author_url(@author), notice: "Um autor foi criado com sucesso!")
        }

        format.json { render(:show, status: :created, location: @author) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @author.errors, status: :unprocessable_entity) }
      end
    end
  end

  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html {
          redirect_to(administrate_author_url(@author), notice: "Um autor foi atualizado com sucesso!")
       }
        format.json { render(:show, status: :ok, location: @author) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @author.errors, status: :unprocessable_entity) }
      end
    end
  end

  def destroy
    respond_to do |format|
      format.html do
        if @author.posts.count > 0
          redirect_to(administrate_authors_path, alert: "Não foi possível apagar o autor!")
        else
          @author.destroy
          redirect_to(administrate_authors_path, notice: "Um autor foi apagado com sucesso!")
        end
      end
      format.json { head(:no_content) }
    end
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(
      :name,
      :description,
      :facebook_profile_url,
      :instagram_profile_url,
      :twitter_profile_url,
      :linkedin_profile_url,
      :youtube_profile_url,
    )
  end
end

app/controllers/administrate/categories_controller.rb
# frozen_string_literal: true
class Administrate::CategoriesController < AdministrateController
  before_action :set_category, only: [ :show, :edit, :update, :destroy, :destroy_cover_image ]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def show
  end

  def create
    @category = Category.new(category_params)
    @category.cover_image.attach(category_params[:cover_image])

    respond_to do |format|
      if @category.save
        format.html {
          redirect_to(administrate_category_url(@category), notice: "Uma categoria foi criada com sucesso!")
        }

        format.json { render(:show, status: :created, location: @category) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @category.errors, status: :unprocessable_entity) }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html {
          redirect_to(administrate_category_url(@category), notice: "Uma categoria foi atualizada com sucesso!")
       }
        format.json { render(:show, status: :ok, location: @category) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @category.errors, status: :unprocessable_entity) }
      end
    end
  end

  def destroy
    respond_to do |format|
      format.html do
        if @category.posts.count > 0
          redirect_to(administrate_categories_path, alert: "Não foi possível apagar a categoria!")
        else
          @category.destroy
          redirect_to(administrate_categories_path, notice: "Uma categoria foi apagada com sucesso!")
        end
      end
      format.json { head(:no_content) }
    end
  end

  def destroy_cover_image
    @category.cover_image.purge

    respond_to do |format|
      format.turbo_stream { render(turbo_stream: turbo_stream.remove(@category)) }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(
      :name,
      :description,
      :cover_image,
    )
  end
end

app/controllers/administrate/dashboards_controller.rb
# frozen_string_literal: true
class Administrate::DashboardsController < AdministrateController
  def index; end
end

app/controllers/administrate/posts_controller.rb
# frozen_string_literal: true
class Administrate::PostsController < AdministrateController
  before_action :set_post, only: [ :show, :edit, :update, :destroy, :destroy_cover_image ]
  before_action :set_categories, only: [:show, :edit, :new]
  before_action :set_authors, only: [:show, :edit, :new]

  # GET /posts or /posts.json
  def index
    @posts = Post.includes(:category).all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.cover_image.attach(post_params[:cover_image])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(administrate_post_url(@post), notice: "Um artigo foi criado com sucesso!") }
        format.json { render(:show, status: :created, location: @post) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @post.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to(administrate_post_url(@post), notice: "Um artigo foi atualizado com sucesso!") }
        format.json { render(:show, status: :ok, location: @post) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @post.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(administrate_posts_path, notice: "Um artigo foi apagado com sucesso!") }
      format.json { head(:no_content) }
    end
  end

  def destroy_cover_image
    @post.cover_image.purge

    respond_to do |format|
      format.turbo_stream { render(turbo_stream: turbo_stream.remove(@post)) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(
        :title,
        :body,
        :cover_image,
        :category_id,
        :author_id,
      )
    end

    def set_categories
      @categories = Category.all
    end

    def set_authors
      @authors = Author.all.order(:name)
    end
end

app/controllers/administrate_controller.rb
# frozen_string_literal: true

class AdministrateController < ApplicationController
  before_action :authenticate_admin!

  layout "administrate"
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @pagy, @categories = pagy(Category.all, items: 8)
  end
end

app/views/administrate/categories/_category.html.erb
<tr>
  <td><%= category.name %></td>
  <td>
    <div class="icons">
      <%= link_to edit_administrate_category_path(category), title:"Editar" do %>
        <%= image_tag "icons/gray/edit.svg" %>
      <% end %>

      <%= link_to [:administrate, category], title:"Visualizar" do %>
        <%= image_tag "icons/gray/eye.svg" %>
      <% end %>

      <%= button_to [:administrate, category], title:"Apagar categoria", data: { turbo: false }, method: :delete, class: "button-transparent" do %>
        <%= image_tag "icons/gray/close.svg" %>
      <% end %>
    </div>
  </td>
</tr>

app/views/administrate/categories/_form.html.erb
<div class="row">
  <%= form_with(model: [:administrate, category], class:"form", id:"category-form") do |form| %>
    <div class="input-row">
      <div class="input-container">
        <%= form.label :name, class:"label" %>
        <%= form.text_field :name, disabled: (params[:action] == "show"), placeholder:"Digite aqui o nome", class:"input" %>
      </div>
    </div>

    <div class="input-row">
      <div class="input-container">
        <%= form.label :description, class:"label" %>
        <%= form.text_field :description, disabled: (params[:action] == "show"), placeholder:"Digite aqui a descrição", class:"input" %>
      </div>
    </div>

    <div class="input-row">
      <div class="input-container">
        <div>
          <%= form.label :cover_image, class:"label label-input-file" %>

          <div id=<%= dom_id(category) %>>
            <%= image_tag category.cover_image if category.cover_image.attached? %>

            <%= link_to "Remover",
                  destroy_cover_image_administrate_category_path(category),
                  data: { "turbo-confirm": "Tem certeza?", "turbo-method": :delete } if category.cover_image.attached? && (params[:action] != "show")%>
          </div>

          <%= form.file_field :cover_image if (params[:action] != "show")%>
        </div>
      </div>
    </div>

    <%= form.submit "Salvar Categoria", style: "display: none;" %>

    <%= button_to "Apagar categoria", [:administrate, category], data: { turbo: false }, method: :delete, class:"button small" if (params[:action] == "show") %>
  <% end %>
</div>

app/views/administrate/categories/edit.html.erb
<h1 class="admin-title">
  <%= link_to "Categorias", administrate_categories_path %>
</h1>
<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Edição de Categoria</h2>
    <div class="buttons">
      <a href="#" class="button small" onclick="document.forms['category-form'].submit()">
        <%= image_tag "icons/white/save.svg" %>
        Salvar categoria
      </a>
    </div>
  </div>

  <%= render "form", category: @category %>

</div>

app/views/administrate/categories/index.html.erb
<h1 class="admin-title">Categorias</h1>
<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Listagem de categorias</h2>
    <div class="buttons">
      <%= link_to new_administrate_category_path, class:"button small" do %>
        <%= image_tag "icons/white/add.svg", alt:"add" %>
        Adicionar nova categoria
      <% end %>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th style="width: 100%;">Nome</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <%= render category %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/administrate/categories/new.html.erb
<h1 class="admin-title">
  <%= link_to "Categorias", administrate_categories_path %>
</h1>
<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Cadastro de Categorias</h2>
    <div class="buttons">
      <a href="#" class="button small" onclick="document.forms['category-form'].submit()">
        <%= image_tag "icons/white/save.svg" %>
        Salvar categoria
      </a>
    </div>
  </div>

  <%= render "form", category: @category %>

</div>

app/views/administrate/categories/show.html.erb
<h1 class="admin-title">
  <%= link_to "Categoria", administrate_categories_path %>
</h1>
<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Visusalizar Categoria</h2>
    <div class="buttons">
      <%= link_to edit_administrate_category_path(@category), class: "button small" do %>
        <%= image_tag "icons/white/edit.svg" %>
        Editar categoria
      <% end %>
    </div>
  </div>

  <%= render "form", category: @category %>

</div>