config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  namespace :administrate do
    get "/", to: "dashboards#index"

    resources :categories do
      member do
        delete "destroy_cover_image"
      end
    end

    resources :authors

    resources :posts do
      member do
        delete "destroy_cover_image"
      end
    end
  end

  resources :posts, only: [:index, :show] do
    member do
      get :category
    end
    resources :comments do
      member do
        post "like"
        post "dislike"
      end
    end
  end

  resources :categories, only: [:index]

  get "/inicio", to: "welcome#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @posts = Post.all.order(updated_at: :desc).limit(6)
    @categories = Category.all.take(8)
  end
end

app/views/welcome/_categories.html.erb
<section class="section categories-grid-section">
  <div class="container">
    <div class="title-container with-item">
      <h2 class="title">Navegue por categoria</h2>
      <%= link_to "Ver todos", categories_path, class: "button" %>
    </div>
    <div class="grid">
      <% @categories.each do |category| %>
        <%= link_to category_post_path(category), class:"item" do %>
          <%= image_tag category.cover_image, alt:"Categoria", class:"item-image" %>
          <div class="item-title"><%= category.name %></div>
          <p class="item-description">
            <%= category.description %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/welcome/_main_banner.html.erb
<section class="section main-banner-section">
  <div class="container">
    <div class="text-container">
      <h1 class="title">Transforme sua carreira como desenvolvedor</h1>
      <h4 class="subtitle">O aprendizado definitivo que você estava procurando para acelerar sua carreira</h4>
    </div>
    <div class="image-container">
      <%= image_tag "main-banner.jpg", alt:"Desenvolvedor com notebook" %>
    </div>
  </div>
</section>

app/views/welcome/_post.html.erb
<%= link_to post_path(post), class:"item" do %>
  <%= image_tag(cover_image_fallback(post), class: "item-image", alt:"post 1")  %>

  <div class="item-row">
    <div class="item-category"><%= post.category.name %></div>
    <div class="item-comments">25</div>
  </div>
  <div class="item-row">
    <div class="item-title">
      <%= post.title %>
    </div>
  </div>
  <div class="item-row">
    <div class="item-author"><%= post.author.name %></div>
    <div class="item-date"><%= post.created_at.strftime("%d de %b") %></div>
  </div>
<% end %>

app/views/welcome/_posts.html.erb
<section class="section posts-grid-section">
  <div class="container">
    <div class="title-container with-item">
      <h2 class="title">Publicações mais recentes</h2>
      <a href="#" class="button">Ver todos</a>
    </div>
    <div class="grid" id="postGridHome">
      <% @posts.each do |post| %>
        <%= render partial: "post", locals: { post: post } %>
      <% end %>
    </div>
    <div class="grid-mobile">
      <div class="bullets" id="postGridHomeBullets"></div>
      <div><a href="#" class="button clean">ver mais</a></div>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<%= render partial: "main_banner" %>
<%= render partial: "posts" %>
<%= render partial: "categories" %>