config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  namespace :administrate do
    get "/", to: "dashboards#index"

    resources :categories do
      member do
        delete "destroy_cover_image"
      end
    end

    resources :authors

    resources :posts do
      member do
        delete "destroy_cover_image"
      end
    end
  end

  resources :posts, only: [:index, :show] do
    member do
      get :category
    end
    resources :comments do
      member do
        post "like"
        post "dislike"
      end
    end
  end

  resources :categories, only: [:index]

  get "/inicio", to: "welcome#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/post.rb
# frozen_string_literal: true
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :category
  belongs_to :author, optional: true

  has_many :comments

  has_one_attached :cover_image do |attachable|
    attachable.variant(:thumb, resize_to_limit: [325, 205])
    attachable.variant(:medium, resize_to_limit: [850, 650])
  end
end

app/controllers/administrate/posts_controller.rb
# frozen_string_literal: true
class Administrate::PostsController < AdministrateController
  before_action :set_post, only: [ :show, :edit, :update, :destroy, :destroy_cover_image ]
  before_action :set_categories, only: [:show, :edit, :new]
  before_action :set_authors, only: [:show, :edit, :new]

  # GET /posts or /posts.json
  def index
    @posts = Post.includes(:category).all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.cover_image.attach(post_params[:cover_image])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(administrate_post_url(@post), notice: "Um artigo foi criado com sucesso!") }
        format.json { render(:show, status: :created, location: @post) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @post.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to(administrate_post_url(@post), notice: "Um artigo foi atualizado com sucesso!") }
        format.json { render(:show, status: :ok, location: @post) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @post.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(administrate_posts_path, notice: "Um artigo foi apagado com sucesso!") }
      format.json { head(:no_content) }
    end
  end

  def destroy_cover_image
    @post.cover_image.purge

    respond_to do |format|
      format.turbo_stream { render(turbo_stream: turbo_stream.remove(@post)) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(
        :title,
        :body,
        :cover_image,
        :category_id,
        :author_id,
      )
    end

    def set_categories
      @categories = Category.all
    end

    def set_authors
      @authors = Author.all.order(:name)
    end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def index
    @pagy, @posts = pagy(Post.all, items: 9)
  end

  def show
    @post = Post.friendly.find(params[:id])
    @other_posts = Post.all.take(3)
    @comments = order_comments_by
  end

  def category
    @category = Category.find_by(id: params[:id])
    @pagy, @posts = pagy(@category.posts, items: 9)
  end

  private

  def order_comments_by
    return @post.comments.order(created_at: :asc) if params[:order_by] == "more_recents"

    @post.comments.order(created_at: :desc)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true
module PostsHelper
  def cover_image_fallback(post, variant = :thumb)
    post.cover_image.attached? ? post.cover_image.variant(variant) : "posts/post1.jpg"
  end

  def markdown(text)
    options = [:hard_wrap, :autolink, :no_intra_emphasis, :fenced_code_blocks]
    Markdown.new(text, *options).to_html.html_safe
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= link_to post_path(post), class:"item" do %>
  <%= image_tag(cover_image_fallback(post), class: "item-image", alt:"post 1")  %>

  <div class="item-row">
    <div class="item-category"><%= post.category.name %></div>
    <div class="item-comments"><%= post.comments.count %></div>
  </div>
  <div class="item-row">
    <div class="item-title">
      <%= post.title %>
    </div>
  </div>
  <div class="item-row">
    <div class="item-author"><%= post.author.name %></div>
    <div class="item-date"><%= post.created_at.strftime("%d de %b") %></div>
  </div>
<% end %>

app/views/posts/category.html.erb
<section class="section all-posts-grid-section">
  <div class="container">
    <div class="title-container with-item">
      <h2 class="title">Listando os posts da categoria [<%= @category.name %>]</h2>
    </div>
    <div class="grid" id="postGridHome">
      <% @posts.each do |post| %>
        <%= render partial: "post", locals: { post: post } %>
      <% end %>
    </div>
    <div class="navigation">
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    </div>
    <div class="grid-mobile">
      <div class="bullets" id="postGridHomeBullets"></div>
      <div><a href="#" class="button clean">ver mais</a></div>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<section class="section all-posts-grid-section">
  <div class="container">
    <div class="title-container with-item">
      <h2 class="title">Listando todos os posts</h2>
    </div>
    <div class="grid" id="postGridHome">
      <% @posts.each do |post| %>
        <%= render partial: "post", locals: { post: post } %>
      <% end %>
    </div>
    <div class="navigation">
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    </div>
    <div class="grid-mobile">
      <div class="bullets" id="postGridHomeBullets"></div>
      <div><a href="#" class="button clean">ver mais</a></div>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<section class="section posts-detail-title-section">
  <div class="container">
    <h1 class="post-detail-title"><%= @post.title %></h1>
  </div>
</section>

<section class="section post-detail-default-section post-detail-image-section">
  <div class="container">
    <div class="primary-content">
      <div class="post-detail-image">
        <%= image_tag(cover_image_fallback(@post, :medium), alt: @post.title) %>
      </div>
    </div>
    <div class="secondary-content">
      <a href="#" class="post-detail-image-ad">
        <%= image_tag "ad/image-ad.jpg" %>
      </a>
      <div class="share-post">
        <div class="share-post-title">Compartilhar post</div>
        <div class="socials">
          <%= link_to "https://www.facebook.com/sharer/sharer.php?u=#{post_url(@post)}" do %>
            <%= image_tag "icons/red/facebook.svg" %>
          <% end %>

          <%= link_to "https://twitter.com/intent/tweet?text=#{@post.title}&url=#{post_url(@post)}" do %>
            <%= image_tag "icons/red/twitter.svg" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section post-detail-default-section author-section">
  <div class="container">
    <div class="primary-content">
      <div class="author">
        <div class="image-container">
          <%= image_tag(avatar_image_fallback(@post.author), alt: @post.author.name) %>
        </div>
        <div class="text-container">
          <div class="label">Autor</div>
          <div class="description"><%= @post.author.name %></div>
        </div>
      </div>
      <div class="category text-container">
        <div class="label">Categoria</div>
        <div class="description"><%= @post.category.name %></div>
      </div>
      <div class="comments text-container">
        <div class="label">Comentários</div>
        <div class="description">15</div>
      </div>
    </div>
  </div>
</section>


<section class="section post-detail-default-section post-content-section">
  <div class="container">
    <div class="primary-content">
      <div class="post-detail-content">
        <%= markdown(@post.body) %>
      </div>
      <div class="post-detail-author-bio">
        <div class="image">
          <%= image_tag(avatar_image_fallback(@post.author), alt: @post.author.name) %>
          <div class="text-mobile">
            <div class="label">sobre o autor</div>
            <div class="author-name"><%= @post.author.name %></div>
          </div>
        </div>
        <div class="text">
          <div class="label">sobre o autor</div>
          <div class="author-name"><%= @post.author.name %></div>
          <div class="author-description">
            <%= @post.author.description %>
          </div>
          <div class="author-social">
            <%= link_to @post.author.facebook_profile_url do %>
              <%= image_tag "icons/gray/facebook.svg" %>
            <% end %>

            <%= link_to @post.author.instagram_profile_url do %>
              <%= image_tag "icons/gray/instagram.svg" %>
            <% end %>

            <%= link_to @post.author.twitter_profile_url do %>
              <%= image_tag "icons/gray/twitter.svg" %>
            <% end %>

            <%= link_to @post.author.linkedin_profile_url do %>
              <%= image_tag "icons/gray/linkedin.svg" %>
            <% end %>

            <%= link_to @post.author.youtube_profile_url do %>
              <%= image_tag "icons/gray/youtube.svg" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="post-detail-comment">
        <div class="comment-title-container">
          <div class="comment-title">Comentários</div>
          <div class="comment-actions">
            <%= form_with(url: post_path(@post), method: :get) do |form| %>
              <div class="label">ordenar por: </div>
              <%= form.select :order_by,
                  options_for_select([["Últimos comentários", "last_comments"],["Mais recentes", "more_recents"]], params[:order_by]),
                  {},
                  { class:"select clean small", onchange:"this.form.submit()" } %>
            <% end %>
          </div>
        </div>
        <div class="comment-form-container">
          <%= form_with(model: [@post, @post.comments.build], data: { turbo: false }) do |form| %>
            <%= form.text_area :body, class:"textarea darker full double-padding", placeholder:"Insira seu comentário aqui..." %>
            <%= form.submit "Publicar", class:"button small" %>
          <% end %>
        </div>
        <div class="post-detail-comments-list">
          <% @comments.each do |comment| %>
            <% next if comment.new_record? %>
            <div class="post-detail-comment-item">
              <div class="author-row">
                <div>
                  <div class="avatar">
                    <%= image_tag "avatar/man-1.svg" %>
                  </div>
                  <div class="name"><%= comment.user.email.split("@").first %></div>
                </div>
                <div>
                  <div class="date"><%= time_ago_in_words(comment.created_at) %></div>
                </div>
              </div>
              <div class="description-row">
                <p>
                  <%= comment.body %>
                </p>
              </div>
              <div class="actions-row">
                <%= button_to like_post_comment_path(@post, comment), class:"like", form: { turbo: false } do %>
                  <%= comment.like %>
                <% end %>

                <%= button_to dislike_post_comment_path(@post, comment), class:"deslike", form: { turbo: false } do %>
                  <%= comment.dislike %>
                <% end %>

                <%= link_to "", "https://twitter.com/intent/tweet?text=#{truncate(comment.body, length: 100)}&url=#{post_url(@post)}", class:"share" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="secondary-content">
      <a href="#" class="post-content-ad">
        <%= image_tag "ad/post-content-ad.jpg" %>
      </a>
      <div class="post-detail-other-posts">
        <div class="other-posts-title">Outras publicações</div>

        <% @other_posts.each do |other_post| %>
          <a href="#" class="post-resume">
            <%= image_tag(cover_image_fallback(other_post, :thumb), alt: other_post.title, class:"post-resume-image") %>
            <h4 class="post-resume-title"><%= other_post.title %></h4>
          </a>
        <% end %>
      </div>
      <a href="#" class="post-content-ad">
        <%= image_tag "ad/post-content-footer-ad.jpg" %>
      </a>
    </div>
  </div>
  </div>
</section>